name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["10.12.0", 10.x, 12.x, 14.x, 15.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install --legacy-peer-deps && npm run install-examples
      env:
        CI: true
    - name: Test
      run: npm run test-cov
